apiVersion: v1
kind: PersistentVolume
metadata:
  name: token-cache-pv
spec:
  capacity:
    storage: 1Gi  # Adjust size as needed
  accessModes:
    - ReadWriteMany  # Change to ReadWriteMany if shared access is needed
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /mnt/k8s/token-cache  # Ensure this exists on all nodes

