apiVersion: v1
kind: ConfigMap
metadata:
  name: pm-producer-config
data:
  application_configuration.json: |
    {
      "types": [
        {
          "id": "PmData",
          "kafkaInputTopic": "json-file-ready-kpadp",
          "useHttpProxy": false,
          "dataType": "pmData",
          "inputJobType": "xml-file-data-to-filestore",
          "inputJobDefinition": {
             "kafkaOutputTopic": "json-file-ready-kpadp"
          }
        }
      ]
    }
  application.yaml: |
    spring:
      profiles:
        active: prod
      main:
        allow-bean-definition-overriding: true
      aop:
        auto: false
    management:
      endpoints:
        web:
          exposure:
            include: "loggers,logfile,health,info,metrics,threaddump,heapdump"
      endpoint:
        shutdown:
          enabled: true
    lifecycle:
      timeout-per-shutdown-phase: "20s"
    logging:
      level:
        ROOT: WARN
        org.apache.kafka: WARN
        org.springframework: ERROR
        org.springframework.data: ERROR
        org.springframework.web.reactive.function.client.ExchangeFunctions: ERROR
        org.oran.pmproducer: TRACE
    server:
      port: 8435
      http-port: 8084
    app:
      ics-base-url: http://ics:8083
      configuration-filepath: /opt/app/pm-producer-service/data/application_configuration.json
      kafka:
        bootstrap-servers: kafka:9097
      auth-token-file: /token-cache/jwt.txt
      pm-files-path: /pm-files
      s3:
        endpointOverride: http://minio-server:9000
        accessKeyId: admin
        secretAccessKey: adminadmin
        locksBucket: pm-files-json-locks
        bucket: pm-files-json

