apiVersion: v1
kind: PersistentVolume
metadata:
  name: token-cache-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /mnt/k8s/token-cache  # Adjust this path on your host

