apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pm-token-cache-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 500Mi

