apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pm-shared-files-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi

