apiVersion: v1
kind: Service
metadata:
  name: pm-producer-json2kafka
spec:
  selector:
    app: pm-producer-json2kafka
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: ClusterIP

