apiVersion: v1
kind: PersistentVolume
metadata:
  name: pm-files-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany  # Allows multiple pods to access the volume
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /mnt/shared-volume  # Ensure this exists on all nodes

